filter:
    excluded_paths:
        - app/tests/*
        - app/views/*
        - app/config/*
        - app/database/*
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_mess_detector: true
    php_cs_fixer:
        filter:
            paths:
                - app/TypiCMS/*
            excluded_paths:
                - app/TypiCMS/Modules/*/Views/*
        config:
            level: psr2
